### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by Definence** [JARVIS-VOVA/excessive-css#1]
> Helping find excessice css styles 

There is a mistake in the word `excessice`. I guess you meant `excessive`.
Also the phrase `Helping find` is totally wrong. It should be `helps in finding` or `helps to find`

**Comment by JARVIS-VOVA** [comment]
@Definence 
Thank you.
I'll change on 'Helps to find'

**Comment by JARVIS-VOVA** [comment]
Fixed in 678f70b
I'll close this
