### ISSUE TITLE
WHY NOT 1_000_000_000_000?)

### ISSUE THREAD

**Issue by Definence** [JARVIS-VOVA/excessive-css#2]
https://github.com/JARVIS-VOVA/excessive-css/blob/e814f8f46a961c1b670c928566a47642caeb6d24/excessive_css.rb#L73

**Comment by Definence** [comment]
Also name your variables for informative. I mean that the `number` is bad name for your var

**Comment by JARVIS-VOVA** [comment]
@Definence, good catch.
Oh, 'magic numbers'.
I agree with you.
Do you have idea for name this variable?

**Comment by Definence** [comment]
number_of_tests, tests_quantity or smth like that

**Comment by JARVIS-VOVA** [comment]
#5

**Comment by JARVIS-VOVA** [comment]
# #5

**Comment by JARVIS-VOVA** [comment]
#5

**Comment by JARVIS-VOVA** [comment]
Fixed in #5
I'll close this.
