### ISSUE TITLE
Move this file to .gitignore

### ISSUE THREAD

**Issue by Definence** [JARVIS-VOVA/excessive-css#3]
https://github.com/JARVIS-VOVA/excessive-css/blob/e814f8f46a961c1b670c928566a47642caeb6d24/excessive_css.txt#L1

**Comment by JARVIS-VOVA** [comment]
@Definence 
I want show result program for other people.
I think this make sense.
I'll close this.

**Comment by Definence** [comment]
@JARVIS-VOVA Don't see any reason to do this, but if you wanna...
